"""initial schema

Revision ID: bc6127ad98c9
Revises: 
Create Date: 2026-02-07 20:58:33.402332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc6127ad98c9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# def upgrade() -> None:
    # """Upgrade schema."""
    # # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('ix_users_email'), table_name='users')
    # op.drop_index(op.f('ix_users_id'), table_name='users')
    # op.drop_table('users')
    # op.drop_index(op.f('ix_accounts_account_number'), table_name='accounts')
    # op.drop_index(op.f('ix_accounts_id'), table_name='accounts')
    # op.drop_table('accounts')
    # # ### end Alembic commands ###


# def downgrade() -> None:
#     """Downgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.create_table('accounts',
#     sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
#     sa.Column('account_number', sa.VARCHAR(), autoincrement=False, nullable=True),
#     sa.Column('balance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
#     sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
#     sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('accounts_user_id_fkey')),
#     sa.PrimaryKeyConstraint('id', name=op.f('accounts_pkey'))
#     )
#     op.create_index(op.f('ix_accounts_id'), 'accounts', ['id'], unique=False)
#     op.create_index(op.f('ix_accounts_account_number'), 'accounts', ['account_number'], unique=True)
#     op.create_table('users',
#     sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
#     sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
#     sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False),
#     sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True),
#     sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
#     )
#     op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
#     op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
#     # ### end Alembic commands ###

def upgrade():
    pass

def downgrade():
    pass
